import httpx
import asyncio

TOKEN = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4NTM3MTBkNDJkNjE4MGNiNzI1M2JkZmYyNTQzZDQ1MCIsImFjY2Vzc1J1bGVzIjpbeyJpZCI6InRyYWRpbmctYWNjb3VudC1tYW5hZ2VtZW50LWFwaSIsIm1ldGhvZHMiOlsidHJhZGluZy1hY2NvdW50LW1hbmFnZW1lbnQtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVzdC1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcnBjLWFwaSIsIm1ldGhvZHMiOlsibWV0YWFwaS1hcGk6d3M6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6Im1ldGFhcGktcmVhbC10aW1lLXN0cmVhbWluZy1hcGkiLCJtZXRob2RzIjpbIm1ldGFhcGktYXBpOndzOnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJtZXRhc3RhdHMtYXBpIiwibWV0aG9kcyI6WyJtZXRhc3RhdHMtYXBpOnJlc3Q6cHVibGljOio6KiJdLCJyb2xlcyI6WyJyZWFkZXIiLCJ3cml0ZXIiXSwicmVzb3VyY2VzIjpbIio6JFVTRVJfSUQkOioiXX0seyJpZCI6InJpc2stbWFuYWdlbWVudC1hcGkiLCJtZXRob2RzIjpbInJpc2stbWFuYWdlbWVudC1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoiY29weWZhY3RvcnktYXBpIiwibWV0aG9kcyI6WyJjb3B5ZmFjdG9yeS1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciIsIndyaXRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfSx7ImlkIjoibXQtbWFuYWdlci1hcGkiLCJtZXRob2RzIjpbIm10LW1hbmFnZXItYXBpOnJlc3Q6ZGVhbGluZzoqOioiLCJtdC1tYW5hZ2VyLWFwaTpyZXN0OnB1YmxpYzoqOioiXSwicm9sZXMiOlsicmVhZGVyIiwid3JpdGVyIl0sInJlc291cmNlcyI6WyIqOiRVU0VSX0lEJDoqIl19LHsiaWQiOiJiaWxsaW5nLWFwaSIsIm1ldGhvZHMiOlsiYmlsbGluZy1hcGk6cmVzdDpwdWJsaWM6KjoqIl0sInJvbGVzIjpbInJlYWRlciJdLCJyZXNvdXJjZXMiOlsiKjokVVNFUl9JRCQ6KiJdfV0sImlnbm9yZVJhdGVMaW1pdHMiOmZhbHNlLCJ0b2tlbklkIjoiMjAyMTAyMTMiLCJpbXBlcnNvbmF0ZWQiOmZhbHNlLCJyZWFsVXNlcklkIjoiODUzNzEwZDQyZDYxODBjYjcyNTNiZGZmMjU0M2Q0NTAiLCJpYXQiOjE3NzMyMjcxMTN9.gyXtvLwz485xAp6dXfNGlt5rDNLRGXoxifVZYCKZObMyoq7NOxamN6f5sYiHZARiW_Suhkokf3WBenJWmqinhAJno-Kci3Sy9oDsIJf9lHkMo7fZlJcHbuptZ2fWlyTN_yrcBIC5KNItHOVSVxj4vgMCfjDRHw1Jr58O8nVqA9ZZIBE_vJAF_VRE3-m5Mec56P8yqL1SoioYjRby4oy3Msr1Qt7H-Q_fjqSGg-IQe1c4De2svHpzpZEwVX9zBl2D0ayWzjRoCkzDV-qIBmpqYHOEWFfvJej0BaHUeO6R30JYR72l_wcrm9t6FwdjisvyQRNwgaaeGAzj0lSoBKzx01CeoJPGczhMbq9qOEWDciDKhrROFoV_GXT2I1WqM7lGorQm_rNGWsHyGm6YPPhrlnKcKumUuv_gPNcX59enZH6yPhHyvxCy8nS3rUMYL5f5bW3hCoP9nmTAzYycQbVNQNJ6RV2oL56aFZZKVjI2MyYVOtACfCMFd_JucK7z0xRewWSG5qfSvO512F0MVUCly-TFhbUhxCA_ZG_79aHQy5U7LoQza1MMdFxiBqxoX-Exa27MvU7TjI8rk450L-4XPDL1qY_HrwlDbz5t1gP_YbJPC-DZvKT8aiBBwTgeirMF5EQ4YmuV28TfGAymZchMMAFc3GtpwHIVLz4Nh0C3KFM"
ACCOUNT_ID = "0951d237-e60c-406b-9ad0-fabeeb9f1087"
MD_URL = "https://mt-market-data-client-api-v1.london.agiliumtrade.ai"

async def test():
    headers = {"auth-token": TOKEN}
    async with httpx.AsyncClient() as client:
        # Test Market Data URL for history
        paths = ["/history-deals", "/history/deals", "/historical-trading-log"]
        for p in paths:
            url = f"{MD_URL}/users/current/accounts/{ACCOUNT_ID}{p}"
            r = await client.get(url)
            print(f"MD {p}: {r.status_code}")

if __name__ == "__main__":
    asyncio.run(test())
